SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `suibian`.`orders` CHANGE COLUMN `status` `status` TINYINT(3) UNSIGNED NOT NULL COMMENT ' /* comment truncated */'  ;

ALTER TABLE `suibian`.`orders_food` ADD COLUMN `num` INT(10) UNSIGNED NOT NULL COMMENT ' /* comment truncated */'  AFTER `food_id` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
